version: "3.8"

services:
  nia-db:
    image: postgres:14
    container_name: nia_crm_db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME:-whaticketsaas}
      POSTGRES_USER: ${DB_USER:-whaticket_user}
      POSTGRES_PASSWORD: ${DB_PASS:-mysql123456}
    ports:
      - "5433:5432"
    volumes:
      - nia_db_data:/var/lib/postgresql/data

  nia-redis:
    image: redis:alpine
    container_name: nia_crm_redis
    restart: always
    ports:
      - "6380:6379"
    volumes:
      - nia_redis_data:/data

  nia-backend:
    image: ghcr.io/ciyei0/nia_crm-backend:latest
    container_name: nia_crm_backend
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=8001
      - DB_DIALECT=postgres
      - DB_HOST=nia-db
      - DB_USER=${DB_USER:-whaticket_user}
      - DB_PASS=${DB_PASS:-mysql123456}
      - DB_NAME=${DB_NAME:-whaticketsaas}
      - DB_PORT=5432 # This is the internal port of nia-db
      - REDIS_URI=redis://nia-redis:6379 # Internal port of nia-redis
      - BACKEND_URL=${BACKEND_URL:-https://niacrmbot.com:8001}
      - FRONTEND_URL=${FRONTEND_URL:-https://niacrmbot.com}
      - PROXY_PORT=8001
      # ... you will need to map other variables from .env here
      - JWT_SECRET=${JWT_SECRET:-kZaOTd+YZpjRUyyuQUpigJaEMk4vcW4YOymKPZX0Ts8=}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET:-dBSXqFg9TaNUEDXVp6fhMTRLBysP+j2DSqf7+raxD3A=}
    ports:
      - "8081:8001"
    depends_on:
      - nia-db
      - nia-redis

  nia-frontend:
    image: ghcr.io/ciyei0/nia_crm-frontend:latest
    container_name: nia_crm_frontend
    restart: always
    ports:
      - "127.0.0.1:3010:3001" # Internal mapping for Nginx proxy
    depends_on:
      - nia-backend
    volumes:
      - ./frontend-build:/usr/share/nginx/html

volumes:
  nia_db_data:
  nia_redis_data:
